// Generated by vpy2cpp from a VPython program.

import std;
import vcpp;
import lam.linearalgebra;

using namespace vcpp;

namespace
{
double dt_{};
double k{};
double m{};
double t{};
vec3 x0{};
} // namespace

task<double> kinetic(vec3 v, double mass, double scale_);
task<void> lift(std::vector<handle<sphere_object>>& group, double dy);
task<vec3> spring_force(vec3 x);
task<void> tick();

task<double> kinetic(vec3 v, double mass, double scale_)
{
  double e = 0.5 * mass * std::pow(mag(v), 2);
  co_return scale_ * e;
}

task<void> lift(std::vector<handle<sphere_object>>& group, double dy)
{
  handle<sphere_object> b{};
  for (std::size_t for__1 = 0; for__1 < group.size(); ++for__1)
  {
    b = group[for__1];
    b.pos = vec3{b.pos.x(), b.pos.y() + dy, b.pos.z()};
  }
  group.push_back(sphere(pos = vec3{0, 3, 0}, radius = 0.1));
  co_return;
}

task<vec3> spring_force(vec3 x)
{
  co_return -k * (x - x0);
}

task<void> tick()
{
  t += dt_;
  co_await rate(100);
  co_return;
}

task<void> vpython_program()
{
  vec3 F{};
  handle<sphere_object> b{};
  double i{};
  double last_x{};
  double n{};
  scene.m_caption = "A ball on a spring";
  // scene.width = 600: not translated; the canvas takes its size from the page
  // scene.height = 600: not translated; the canvas takes its size from the page
  scene.set_center(vec3{0, 0, 0});
  scene.set_forward(vec3{0, -0.2, -1});
  scene.set_range(3);
  scene.m_userzoom = false;
  k = 4;
  m = 0.5;
  x0 = vec3{1, 0, 0};
  auto anchor = box(pos = vec3{-2, 0, 0}, size = vec3{0.2, 1, 1}, color = colors::gray(0.5), texture = textures::wood);
  auto ball = sphere(pos = x0, radius = 0.2, color = colors::cyan, make_trail = true, retain = 100);
  vec3 ball_v = vec3{0, 0.5, 0};
  dt_ = 0.01;
  t = 0;
  double t_start = 0;
  while (t < 10)
  {
    co_await tick();
    F = (co_await spring_force(ball.pos));
    ball_v = ball_v + F / m * dt_;
    ball.pos = ball.pos + ball_v * dt_;
    last_x = ball.pos.x();
    if (ball.pos.x() > 2 || !(-1 < ball.pos.y() && ball.pos.y() < 1))
    {
      ball.color = colors::red;
    }
    else if ((co_await kinetic(ball_v, m, 0.5)) > 1 || (co_await kinetic(ball_v, m, 1)) > 2)
    {
      ball.color = colors::yellow;
    }
    else
    {
      ball.color = colors::cyan;
    }
  }
  ball.pos = vec3{last_x, 0, 0};
  std::vector<handle<sphere_object>> balls;
  for (i = 0; i < 5; i += 1)
  {
    balls.push_back(sphere(pos = vec3{i, 2, 0}, radius = 0.1));
  }
  std::vector<double> heights = {0.5, 1, 1.5};
  for (n = static_cast<double>(heights.size()) - 1; n > -1; n += -1)
  {
    heights[static_cast<std::size_t>(n)] = heights[static_cast<std::size_t>(n)] * 2;
  }
  for (std::size_t for__1 = 0; for__1 < balls.size(); ++for__1)
  {
    b = balls[for__1];
    b.color = colors::green;
  }
  balls[balls.size() - 1].radius = heights[0];
  co_await lift(balls, 0.5);
  std::string skin = textures::metal;
  anchor.texture = skin;
  scene.m_title = std::format("{} balls, the first at x = {:.2f}", static_cast<double>(balls.size()), balls[0].pos.x());
  scene.append_to_title(" {braces}");
  scene.append_to_caption(std::format("{} {} {}", "t =", t, "steps"));
  auto trailing = sphere(pos = vec3{0, -1, 0}, radius = 0.1, make_trail = true, trail_type = "points");
  auto spinner = box(pos = vec3{2, 2, 0}, axis = vec3{1, 1, 0});
  for (i = 0; i < 3; i += 1)
  {
    spinner.rotate(0.1, vec3{0, 0, 1});
  }
  spinner.rotate(0.2, vec3{0, 1, 0}, vec3{0, 0, 0});
  spinner.rotate(std::numbers::pi / 4);
  vec3 tilted = rotate(vec3{1, 0, 0}, 0.5, vec3{0, 1, 0});
  tilted = rotate(tilted, 0.5);
  spinner.length = 1.0 / 2 + 2 * (3 - 1);
  tilted = 2.0 * tilted;
  tilted *= 3.0;
  spinner.pos = vec3{spinner.pos.x() + 1, spinner.pos.y(), spinner.pos.z()};
  trailing.radius *= 2;
  auto path = curve(color = colors::yellow, radius = 0.05);
  path.append(vec3{0, 0, 0});
  path.append(std::vector<vec3>{vec3{1, 0, 0}, vec3{1, 1, 0}});
  path.append(pos = vec3{0, 1, 0}, color = colors::cyan, radius = 0.1);
  path.modify(1, color = colors::red);
  path.modify(-1, vec3{0, 2, 0});
  vec3 was = path.point(1).color;
  path.modify(1, color = was);
  vec3 drift = random_vec() * random();
  if (path.npoints > 3)
  {
    path.clear();
  }
  scene.m_ambient = 0.5 * colors::white;
  scene.clear_lights();
  auto sun = distant_light(direction = vec3{0, 1, 0}, color = colors::yellow);
  sun.direction = vec3{1, 1, 0};
  auto glow = attach_light(anchor, offset = vec3{0, 1, 0});
  local_light(pos = vec3{0, 3, 0}, color = colors::gray(0.5));
  anchor.emissive = true;
  co_return;
}
