// Generated by vpy2cpp from a VPython program.

import std;
import vcpp;
import lam.linearalgebra;

using namespace vcpp;

namespace
{
vec3 F{};
handle<box_object> anchor{};
handle<sphere_object> b{};
handle<sphere_object> ball{};
vec3 ball__v{};
std::vector<handle<sphere_object>> balls{};
double dt_{};
std::vector<double> heights{};
double i{};
double k{};
double last_x{};
double m{};
double n{};
std::string skin{};
double t{};
double t_start{};
handle<sphere_object> trailing{};
vec3 x0{};
} // namespace

task<double> kinetic(vec3 v, double mass_, double scale);
task<void> lift(std::vector<handle<sphere_object>>& group_, double dy);
task<vec3> spring_force(vec3 x);
task<void> tick();

task<double> kinetic(vec3 v, double mass_, double scale)
{
  double e{};
  e = ((0.5 * mass_) * std::pow(mag(v), 2.0));
  co_return (scale * e);
}

task<void> lift(std::vector<handle<sphere_object>>& group_, double dy)
{
  handle<sphere_object> b{};
  for (std::size_t for__1 = 0; for__1 < group_.size(); ++for__1)
  {
    b = group_[for__1];
    b->m_pos.y() = (b->m_pos.y() + dy);
  }
  group_.push_back(scene.add(sphere(pos = vec3{0.0, 3.0, 0.0}, radius = 0.1)));
  co_return;
}

task<vec3> spring_force(vec3 x)
{
  co_return (-k * (x - x0));
}

task<void> tick()
{
  t = t + (dt_);
  co_await rate(100.0);
  co_return;
}

task<void> vpython_program()
{
  scene.m_caption = "A ball on a spring";
  // scene.width = 600.0: not translated; the canvas takes its size from the page
  // scene.height = 600.0: not translated; the canvas takes its size from the page
  scene.set_center(vec3{0.0, 0.0, 0.0});
  scene.set_forward(vec3{0.0, -0.2, -1.0});
  scene.set_range(3.0);
  scene.m_userzoom = false;
  k = 4.0;
  m = 0.5;
  x0 = vec3{1.0, 0.0, 0.0};
  anchor = scene.add(box(pos = vec3{-2.0, 0.0, 0.0}, size = vec3{0.2, 1.0, 1.0}, color = colors::gray(0.5), texture = textures::wood));
  ball = scene.add(sphere(pos = x0, radius = 0.2, color = colors::cyan, make_trail = true, retain = 100));
  ball__v = vec3{0.0, 0.5, 0.0};
  dt_ = 0.01;
  t = 0.0;
  t_start = 0.0;
  while (t < 10.0)
  {
    co_await tick();
    F = (co_await spring_force(ball->m_pos));
    ball__v = (ball__v + ((F / m) * dt_));
    ball.set_pos((ball->m_pos + (ball__v * dt_)));
    last_x = ball->m_pos.x();
    if ((ball->m_pos.x() > 2.0 || !((-1.0 < ball->m_pos.y() && ball->m_pos.y() < 1.0))))
    {
      ball->m_color = colors::red;
    }
    else if (((co_await kinetic(ball__v, m, 0.5)) > 1.0 || (co_await kinetic(ball__v, m, 1.0)) > 2.0))
    {
      ball->m_color = colors::yellow;
    }
    else
    {
      ball->m_color = colors::cyan;
    }
  }
  ball.set_pos(vec3{last_x, 0.0, 0.0});
  balls = {};
  for (i = 0.0; i < 5.0; i += 1.0)
  {
    balls.push_back(scene.add(sphere(pos = vec3{i, 2.0, 0.0}, radius = 0.1)));
  }
  heights = std::vector<double>{0.5, 1.0, 1.5};
  for (n = (static_cast<double>(heights.size()) - 1.0); n > -1.0; n += -1.0)
  {
    heights[static_cast<std::size_t>(n)] = (heights[static_cast<std::size_t>(n)] * 2.0);
  }
  for (std::size_t for__1 = 0; for__1 < balls.size(); ++for__1)
  {
    b = balls[for__1];
    b->m_color = colors::green;
  }
  balls[balls.size() - 1]->m_radius = heights[0];
  co_await lift(balls, 0.5);
  skin = textures::metal;
  anchor->m_texture = skin;
  scene.m_title = std::format("{} balls, the first at x = {:.2f}", static_cast<double>(balls.size()), balls[0]->m_pos.x());
  scene.append_to_title(" {braces}");
  scene.append_to_caption(std::format("{} {} {}", "t =", t, "steps"));
  trailing = scene.add(sphere(pos = vec3{0.0, -1.0, 0.0}, radius = 0.1, make_trail = true, trail_type = "points"));
  co_return;
}
