/*
 *  vpy2cpp:emit - Writes a VPython program, given as vpy_ast.py's JSON, as vcpp C++
 *
 *  The output declares the top-level variables the program's functions share, then each function (a
 *  coroutine, since any of them may wait in rate()), then vpython_program(), which runs the top-level
 *  statements for vcpp's run_program(). Other variables are locals, declared where they are first
 *  assigned if that is outside any block, else at the top of their function. A first pass works out every
 *  variable's type, and each function's parameter and return types from how it is called; a second writes
 *  the code. Anything vcpp can't express yet stops translation with its line number.
 */

module;

import std;

export module vpy2cpp:emit;

import :json;

export namespace vpy2cpp
{

struct translate_error : std::runtime_error
{
  int line;
  translate_error(int l, const std::string& what) : std::runtime_error(what), line(l) {}
};

class emitter
{
public:
  std::string program(const json& module)
  {
    const auto& body = module["body"].items();
    for (const auto& stmt : body)
      if (stmt["_type"].string() == "FunctionDef")
        declare_function(stmt);
    walk(module, [&](const json& node) {
      const json& t = node["_type"];
      if (t.is_null())
        return;
      if (t.string() == "keyword" && !node["arg"].is_null())
        m_keywords.insert(node["arg"].string());
      else if (t.string() == "Name")
        m_names.insert(node["id"].string());
      else if (t.string() == "arg")
        m_names.insert(node["arg"].string());
    });
    for (const auto& [name, f] : m_functions)
      collect_shared(f);

    // Pass 1: types. Functions are analysed at their first call, with that call's argument types
    m_emit = false;
    for (const auto& stmt : body)
      if (stmt["_type"].string() != "FunctionDef")
        statement(stmt);
    for (const auto& [name, f] : m_functions)
      if (!f.analyzed)
        throw translate_error(line_of(*f.def),
                              std::format("not supported yet: {} is never called (callbacks are not handled)", name));

    // Pass 2: code
    m_emit = true;
    std::string out = "// Generated by vpy2cpp from a VPython program.\n\nimport std;\nimport vcpp;\n"
                      "import lam.linearalgebra;\n\nusing namespace vcpp;\n\n";
    std::string shared;
    for (const auto& [name, t] : m_globals)
      if (m_shared.contains(name))
        shared += std::format("{} {}{{}};\n", cpp_type(t, name), cpp_name(name));
    if (!shared.empty())
      out += "namespace\n{\n" + shared + "} // namespace\n\n";
    for (const auto& [name, f] : m_functions)
      out += signature(name, f) + ";\n";
    if (!m_functions.empty())
      out += "\n";
    for (auto& [name, f] : m_functions)
    {
      begin_body();
      m_fn = &f;
      for (const auto& stmt : (*f.def)["body"].items())
        statement(stmt);
      // Without a co_return or co_await the function wouldn't be a coroutine, and would return no task
      if (f.returns.k == kind::unknown)
        line("co_return;");
      std::string locals;
      for (const auto& [local, t] : f.local_types)
        if (!is_param(local) && !m_declared.contains(local))
          locals += std::format("  {} {}{{}};\n", cpp_type(t, local), cpp_name(local));
      m_fn = nullptr;
      out += signature(name, f) + "\n{\n" + locals + m_out + "}\n\n";
    }
    begin_body();
    for (const auto& stmt : body)
      if (stmt["_type"].string() != "FunctionDef")
        statement(stmt);
    line("co_return;"); // as in each function: it makes vpython_program a coroutine even without rate()
    std::string locals;
    for (const auto& [name, t] : m_globals)
      if (!m_shared.contains(name) && !m_declared.contains(name))
        locals += std::format("  {} {}{{}};\n", cpp_type(t, name), cpp_name(name));
    return out + "task<void> vpython_program()\n{\n" + locals + m_out + "}\n";
  }

private:
  enum class kind
  {
    unknown,
    number,
    boolean,
    string,
    vector,
    object,
    list
  };

  struct type
  {
    kind k = kind::unknown;
    std::string object;        // the vcpp factory for an object: "box", "sphere", ...
    std::vector<type> element; // a list's element type: one entry, unknown until something is put in it

    static type list_of(type t) { return {kind::list, {}, {std::move(t)}}; }
  };

  // Fills in what `into` doesn't know yet from `from`; false if they disagree. A list's element type is
  // often learned after the list is made, from `p = []` then `p.append(x)`.
  static bool unify(type& into, const type& from)
  {
    if (from.k == kind::unknown)
      return true;
    if (into.k == kind::unknown)
    {
      into = from;
      return true;
    }
    if (into.k != from.k || into.object != from.object)
      return false;
    return into.k != kind::list || unify(into.element[0], from.element[0]);
  }

  // How tightly an expression's code binds, to parenthesise only where C++ needs it
  enum precedence
  {
    p_or = 1,
    p_and = 2,
    p_compare = 4,
    p_add = 6,
    p_multiply = 7,
    p_unary = 8,
    p_atom = 10
  };

  struct expr
  {
    std::string code;
    type t;
    int prec = p_atom;
    bool integer = false; // made of integer literals: C++ would divide it as an int
  };

  // A def: its locals are every name it assigns that it doesn't declare global, as in Python
  struct function_info
  {
    const json* def = nullptr;
    std::vector<std::string> params;
    std::vector<type> param_types;
    std::vector<const json*> defaults; // each parameter's default value, or null
    std::set<std::string> assigned;
    std::set<std::string> globals;
    std::map<std::string, type> local_types; // parameters and locals
    type returns;                            // kind::unknown: returns nothing
    bool analyzed = false;
    bool analyzing = false;
  };

  std::string m_out;
  int m_depth = 1;
  bool m_emit = true;
  std::map<std::string, type> m_globals; // top-level variables, and attributes added to top-level objects
  std::map<std::string, function_info> m_functions;
  function_info* m_fn = nullptr; // the function being analysed or written; null at top level
  int m_loops = 0;               // numbers the counters for loops
  std::set<std::string> m_keywords; // every keyword argument's name: those symbols must stay visible
  std::set<std::string> m_names;    // every name the program uses
  std::set<std::string> m_shared;   // top-level names the functions use: these live outside vpython_program
  std::map<std::pair<std::string, std::string>, std::string> m_user_attributes; // (object, attribute): variable
  std::set<std::string> m_seen;     // in the body being written: names assigned so far
  std::set<std::string> m_declared; // and those declared where first assigned

  // ---------------------------------------------------------------- names

  static bool is_object_factory(std::string_view name)
  {
    static constexpr std::array names{"box",   "sphere", "cylinder", "cone",   "pyramid", "ellipsoid", "ring",
                                      "helix", "arrow",  "curve",    "points", "label",   "text",      "extrusion"};
    return std::ranges::find(names, name) != names.end();
  }

  static std::string_view vcpp_factory(std::string_view name) { return name == "text" ? "text3d" : name; }

  // vcpp's named-parameter symbols (vcpp-props.cppm; tests/check_reserved.cmake checks this list against it).
  // A local may take one of these names unless the program also passes an argument by it; a variable outside
  // any function never may, as `using namespace vcpp` would make the name ambiguous.
  static bool named_parameter(std::string_view name)
  {
    // clang-format off
    static const std::set<std::string_view> names{
      "acceleration", "align", "ambient", "axis", "background", "billboard", "border", "box", "caption", "ccw",
      "center", "charge", "closed", "coils", "color", "delta", "depth", "dot_color", "dot_radius", "dt", "emissive",
      "end_normal", "fast", "font", "foreground", "forward", "fov", "graph_ref", "group", "headlength", "headwidth",
      "height", "interval", "label", "legend", "length", "lights", "line", "make_trail", "marker_radius", "markers",
      "mass", "momentum", "normal", "opacity", "path", "points", "pos", "radius", "range", "retain", "round", "scale",
      "shaftwidth", "shape", "sharp_joints", "shininess", "show_dot", "show_end_face", "show_start_face", "size",
      "smooth", "smooth_joints", "start_normal", "target_canvas", "texpos", "text", "texture", "thickness", "title",
      "trail_color", "trail_radius", "trail_type", "twist", "up", "v0", "v1", "v2", "v3", "velocity", "visible",
      "width", "xmax", "xmin", "xoffset", "xscale", "xtitle", "ymax", "ymin", "yoffset", "yscale", "ytitle"};
    // clang-format on
    return names.contains(name);
  }

  // Names a program variable can't keep anywhere: vcpp's functions, and C++ keywords
  static bool reserved(std::string_view name)
  {
    static const std::set<std::string_view> names{
      // vcpp functions and objects the generated code uses
      "scene", "rate", "sleep", "vec3", "vec2", "colors", "mag", "hat", "norm", "cross", "dot", "task", "rotate",
      "random", "random_vec",
      // C++ keywords that are valid Python names
      "auto", "bool", "break", "case", "catch", "char", "class", "const", "default", "delete", "do", "double", "enum",
      "explicit", "extern", "float", "friend", "goto", "inline", "int", "long", "mutable", "namespace", "new",
      "operator", "private", "protected", "public", "register", "short", "signed", "sizeof", "static", "struct",
      "switch", "template", "this", "throw", "typedef", "typename", "union", "unsigned", "using", "virtual", "void",
      "volatile"};
    return names.contains(name) || is_object_factory(name);
  }

  std::string cpp_name(const std::string& name) const
  {
    const bool clash =
      reserved(name) ||
      (named_parameter(name) && (m_keywords.contains(name) || m_shared.contains(name) || m_functions.contains(name)));
    return clash ? name + "_" : name;
  }

  static void walk(const json& node, const auto& visit)
  {
    visit(node);
    if (const auto* a = std::get_if<json::array>(&node.value))
      for (const auto& item : *a)
        walk(item, visit);
    else if (const auto* o = std::get_if<json::object>(&node.value))
      for (const auto& [key, value] : *o)
        walk(value, visit);
  }

  // ---------------------------------------------------------------- helpers

  static int line_of(const json& node)
  {
    const json& l = node["lineno"];
    return l.is_null() ? 0 : std::stoi(l.num().text);
  }

  [[noreturn]] static void unsupported(const json& node, std::string_view what)
  { throw translate_error(line_of(node), std::format("not supported yet: {}", what)); }

  void line(const std::string& text)
  {
    if (!m_emit)
      return;
    m_out.append(static_cast<std::size_t>(m_depth) * 2, ' ');
    m_out += text;
    m_out += '\n';
  }

  // The type of an attribute vcpp's objects have (as handle<T> members); nothing for one a program adds
  static std::optional<kind> object_attribute(std::string_view name)
  {
    static const std::map<std::string_view, kind> attrs{
      {"pos", kind::vector},        {"axis", kind::vector},         {"up", kind::vector},
      {"size", kind::vector},       {"color", kind::vector},        {"trail_color", kind::vector},
      {"background", kind::vector}, {"length", kind::number},       {"height", kind::number},
      {"width", kind::number},      {"radius", kind::number},       {"thickness", kind::number},
      {"opacity", kind::number},    {"shininess", kind::number},    {"retain", kind::number},
      {"interval", kind::number},   {"trail_radius", kind::number}, {"shaftwidth", kind::number},
      {"headwidth", kind::number},  {"headlength", kind::number},   {"coils", kind::number},
      {"xoffset", kind::number},    {"yoffset", kind::number},      {"border", kind::number},
      {"visible", kind::boolean},   {"make_trail", kind::boolean},  {"emissive", kind::boolean},
      {"ccw", kind::boolean},       {"texture", kind::string},      {"trail_type", kind::string},
      {"text", kind::string},       {"font", kind::string},         {"npoints", kind::number},
    };
    const auto it = attrs.find(name);
    return it == attrs.end() ? std::nullopt : std::optional{it->second};
  }

  static std::string paren(const expr& e, int prec) { return e.prec < prec ? "(" + e.code + ")" : e.code; }

  // An integer-valued expression as a double, where C++ would otherwise use int arithmetic or find no
  // operator (lam's vectors scale only by doubles)
  static std::string as_double(const expr& e)
  {
    if (!e.integer)
      return e.code;
    if (std::ranges::all_of(e.code, [](char c) { return std::isdigit(static_cast<unsigned char>(c)) || c == '-'; }))
      return e.code + ".0";
    return std::format("static_cast<double>({})", e.code);
  }

  bool is_param(const std::string& name) const
  { return m_fn && std::ranges::find(m_fn->params, name) != m_fn->params.end(); }

  void begin_body()
  {
    m_out.clear();
    m_loops = 0;
    m_seen.clear();
    m_declared.clear();
  }

  // Whether this assignment declares the variable: its first, outside any block, of a local
  bool declare_here(const std::string& name)
  {
    const bool first = m_seen.insert(name).second;
    const bool local = m_fn ? is_local(name) && !is_param(name) : !m_shared.contains(name);
    if (!first || m_depth != 1 || !local)
      return false;
    m_declared.insert(name);
    return true;
  }

  // ---------------------------------------------------------------- statements

  void statement(const json& s)
  {
    const std::string& t = s["_type"].string();
    if (t == "Expr")
      expression_statement(s);
    else if (t == "Assign")
      assign(s);
    else if (t == "AugAssign")
      aug_assign(s);
    else if (t == "While")
      while_loop(s);
    else if (t == "If")
      if_chain(s);
    else if (t == "For")
      for_loop(s);
    else if (t == "Return")
      return_statement(s);
    else if (t == "Global")
      ; // collected with the function's names
    else if (t == "FunctionDef")
      unsupported(s, "a def inside another block");
    else if (t == "Pass")
      line(";");
    else if (t == "Break")
      line("break;");
    else if (t == "Continue")
      line("continue;");
    else
      unsupported(s, std::format("the {} statement", t));
  }

  void block(const json& body)
  {
    ++m_depth;
    for (const auto& stmt : body.items())
      statement(stmt);
    --m_depth;
  }

  void expression_statement(const json& s)
  {
    const json& value = s["value"];
    const std::string& t = value["_type"].string();
    if (t == "Constant" && std::holds_alternative<std::string>(value["value"].value))
      return; // a docstring
    if (t == "Call" && value["func"]["_type"].string() == "Name")
    {
      const std::string& f = value["func"]["id"].string();
      if (f == "rate" || f == "sleep")
      {
        line(std::format("co_await {};", call(value).code));
        return;
      }
      if (m_functions.contains(f))
      {
        const expr c = call(value);
        line(c.code.substr(1, c.code.size() - 2) + ";"); // drop the parentheses around co_await
        return;
      }
    }
    line(expression(value).code + ";");
  }

  void assign(const json& s)
  {
    // a = b = value gives every target the same value, left to right. The value is computed once unless
    // it is a constant or a name, so a = b = sphere() makes one sphere
    const auto& targets = s["targets"].items();
    const std::string& v = s["value"]["_type"].string();
    const bool repeat = v == "Constant" || v == "Name";
    assign_to(targets[0], s["value"], s);
    for (std::size_t i = 1; i < targets.size(); ++i)
      assign_to(targets[i], repeat ? s["value"] : targets[0], s);
  }

  void assign_to(const json& target, const json& value_node, const json& s)
  {
    const std::string& t = target["_type"].string();
    if (t == "Name")
    {
      store(target["id"].string(), expression(value_node), s);
      return;
    }
    if (t == "Attribute")
    {
      assign_attribute(target, expression(value_node), s);
      return;
    }
    if (t == "Subscript")
    {
      assign_item(target, expression(value_node), s);
      return;
    }
    unsupported(s, std::format("assigning to a {}", t));
  }

  void assign_attribute(const json& target, const expr& value, const json& s)
  {
    const json& base = target["value"];
    const std::string& attr = target["attr"].string();

    if (base["_type"].string() == "Name" && base["id"].string() == "scene")
    {
      static const std::map<std::string_view, std::string_view> scene_members{
        {"caption", "m_caption"},     {"title", "m_title"},       {"background", "m_background"},
        {"autoscale", "m_autoscale"}, {"userspin", "m_userspin"}, {"userzoom", "m_userzoom"}};
      static const std::set<std::string_view> scene_setters{"center", "forward", "range", "fov"};
      if (const auto it = scene_members.find(attr); it != scene_members.end())
        line(std::format("scene.{} = {};", it->second, value.code));
      else if (scene_setters.contains(attr))
        line(std::format("scene.set_{}({});", attr, value.code));
      else if (attr == "width" || attr == "height")
        line(
          std::format("// scene.{} = {}: not translated; the canvas takes its size from the page", attr, value.code));
      else
        unsupported(s, std::format("setting scene.{}", attr));
      return;
    }

    const expr owner = expression(base);
    if (owner.t.k == kind::object)
    {
      if (object_attribute(attr))
      {
        line(std::format("{}.{} = {};", paren(owner, p_atom), attr, value.code));
        return;
      }
      // VPython objects take new attributes; each becomes a variable beside the object's own
      store(user_attribute(base, attr, s), value, s);
      return;
    }
    if (owner.t.k == kind::vector && (attr == "x" || attr == "y" || attr == "z"))
    {
      // One component of an object's vector: the whole vector is set, so its rules apply (pos adds to a trail)
      if (object_vector(base))
      {
        std::string parts;
        for (const char* c : {"x", "y", "z"})
          parts += std::format("{}{}", parts.empty() ? "" : ", ",
                               attr == c ? value.code : std::format("{}.{}()", owner.code, c));
        line(std::format("{} = vec3{{{}}};", owner.code, parts));
      }
      else
        line(std::format("{}.{}() = {};", paren(owner, p_atom), attr, value.code));
      return;
    }
    unsupported(s, std::format("setting .{} here", attr));
  }

  void assign_item(const json& target, const expr& value, const json& s)
  {
    const expr item = subscript(target);
    if (type* list = variable_type(target["value"]); list && !unify(list->element[0], value.t))
      unsupported(s, "a list of different types");
    line(std::format("{} = {};", item.code, value.code));
  }

  void aug_assign(const json& s)
  {
    static const std::map<std::string_view, std::string_view> ops{
      {"Add", "+"}, {"Sub", "-"}, {"Mult", "*"}, {"Div", "/"}};
    const auto it = ops.find(s["op"]["_type"].string());
    if (it == ops.end())
      unsupported(s, std::format("the augmented operator {}", s["op"]["_type"].string()));
    const json& target = s["target"];
    const expr current = expression(target);
    const expr value = expression(s["value"]);
    const type t = result_type(current.t, value.t);
    // A component of an object's vector is set as the whole vector, as an assignment to it is
    if (target["_type"].string() == "Attribute" && current.t.k == kind::number && object_vector(target["value"]))
    {
      assign_computed(target, {std::format("{} {} {}", current.code, it->second, paren(value, p_multiply + 1)), t}, s);
      return;
    }
    if (type* var = variable_type(target); var && !unify(*var, t))
      unsupported(s, std::format("{} holding values of different types", current.code));
    const bool scale = current.t.k == kind::vector && value.t.k == kind::number;
    line(std::format("{} {}= {};", current.code, it->second, scale ? as_double(value) : value.code));
  }

  // Whether e is one of an object's vector attributes, such as ball.pos
  bool object_vector(const json& e)
  {
    return e["_type"].string() == "Attribute" && expression(e["value"]).t.k == kind::object &&
           object_attribute(e["attr"].string()) == kind::vector;
  }

  void assign_computed(const json& target, const expr& value, const json& s)
  {
    const std::string& t = target["_type"].string();
    if (t == "Name")
    {
      store(target["id"].string(), value, s);
    }
    else if (t == "Attribute")
      assign_attribute(target, value, s);
    else if (t == "Subscript")
      assign_item(target, value, s);
    else
      unsupported(s, std::format("updating a {}", t));
  }

  void while_loop(const json& s)
  {
    if (!s["orelse"].items().empty())
      unsupported(s, "while ... else");
    line(std::format("while ({})", condition(s["test"])));
    line("{");
    block(s["body"]);
    line("}");
  }

  void if_chain(const json& s, std::string_view prefix = "")
  {
    line(std::format("{}if ({})", prefix, condition(s["test"])));
    line("{");
    block(s["body"]);
    line("}");
    const auto& orelse = s["orelse"].items();
    if (orelse.empty())
      return;
    if (orelse.size() == 1 && orelse[0]["_type"].string() == "If")
    {
      if_chain(orelse[0], "else "); // elif
      return;
    }
    line("else");
    line("{");
    block(s["orelse"]);
    line("}");
  }

  // for i in range(...) counts in a double, like every VPython number. for x in a_list walks it by index,
  // so items appended inside the loop are reached, as in Python. The loop variable lives on after the loop,
  // as in Python, but a range loop leaves it at the stop value rather than the last one.
  void for_loop(const json& s)
  {
    if (!s["orelse"].items().empty())
      unsupported(s, "for ... else");
    const json& target = s["target"];
    if (target["_type"].string() != "Name")
      unsupported(s, "a for loop over several names at once");
    const std::string& name = target["id"].string();
    const json& iter = s["iter"];
    if (iter["_type"].string() == "Call" && iter["func"]["_type"].string() == "Name" &&
        iter["func"]["id"].string() == "range")
    {
      range_loop(s, name, iter);
      return;
    }
    const expr list = expression(iter);
    if (list.t.k != kind::list)
      unsupported(s, "a for loop over something other than range() or a list");
    if (iter["_type"].string() != "Name")
      unsupported(s, "a for loop over a list that isn't in a variable");
    store_type(name, list.t.element[0], s);
    const std::string n = std::format("for__{}", ++m_loops);
    line(std::format("for (std::size_t {0} = 0; {0} < {1}.size(); ++{0})", n, list.code));
    line("{");
    ++m_depth;
    line(std::format("{} = {}[{}];", cpp_name(name), list.code, n));
    --m_depth;
    block(s["body"]);
    line("}");
  }

  void range_loop(const json& s, const std::string& name, const json& call)
  {
    if (!call["keywords"].items().empty())
      unsupported(call, "keyword arguments to range()");
    const auto& args = call["args"].items();
    if (args.empty() || args.size() > 3)
      unsupported(call, "range() with this many arguments");
    std::vector<std::string> v;
    for (const auto& a : args)
      v.push_back(expression(a).code);
    const std::string start = args.size() == 1 ? "0" : v[0];
    const std::string stop = args.size() == 1 ? v[0] : v[1];
    const std::string step = args.size() == 3 ? v[2] : "1";
    const auto sign = args.size() == 3 ? constant_sign(args[2]) : std::optional{1};
    store_type(name, {kind::number, {}}, s);
    const std::string i = cpp_name(name);
    // Python works out the stop value once. It is kept in a variable unless it is a constant or a name
    // (a name the loop changes is read again each time round)
    const json& stop_node = args[args.size() == 1 ? 0 : 1];
    const bool fixed = stop_node["_type"].string() == "Name" || constant_sign(stop_node);
    const std::string end = fixed ? stop : std::format("for__{}", ++m_loops);
    if (!fixed)
    {
      line("{");
      ++m_depth;
      line(std::format("const double {} = {};", end, stop));
    }
    std::string test;
    if (sign)
      test = std::format("{} {} {}", i, *sign < 0 ? ">" : "<", end);
    else // a step known only when the program runs
      test = std::format("({0} > 0 ? {1} < {2} : {1} > {2})", step, i, end);
    line(std::format("for ({0} = {1}; {2}; {0} += {3})", i, start, test, step));
    line("{");
    block(s["body"]);
    line("}");
    if (!fixed)
    {
      --m_depth;
      line("}");
    }
  }

  // The sign of a numeric literal, or of -literal; nothing for anything else
  static std::optional<int> constant_sign(const json& e)
  {
    if (e["_type"].string() == "UnaryOp" && e["op"]["_type"].string() == "USub")
    {
      const auto inner = constant_sign(e["operand"]);
      return inner ? std::optional{-*inner} : std::nullopt;
    }
    if (e["_type"].string() != "Constant" || !std::holds_alternative<json::number>(e["value"].value))
      return std::nullopt;
    const std::string& text = e["value"].num().text;
    return text.starts_with('-') ? -1 : (std::stod(text) == 0 ? 0 : 1);
  }

  // Records a variable's type where no assignment is written, as for a loop variable
  void store_type(const std::string& name, const type& t, const json& s)
  {
    if (!unify(slot(name), t))
      unsupported(s, std::format("{} holding values of different types", name));
    m_seen.insert(name);
  }

  std::string condition(const json& test)
  {
    const expr e = expression(test);
    return e.code;
  }

  // ---------------------------------------------------------------- scopes and functions

  bool is_local(const std::string& name) const
  {
    return m_fn && !m_fn->globals.contains(name) && (m_fn->assigned.contains(name) || m_fn->local_types.contains(name));
  }

  // The type recorded for a variable, in the scope Python would find it in
  type& slot(const std::string& name) { return is_local(name) ? m_fn->local_types[name] : m_globals[name]; }

  void store(const std::string& name, const expr& value, const json& s)
  {
    type& t = slot(name);
    if (!unify(t, value.t))
      unsupported(s, std::format("{} holding values of different types", name));
    if (!m_emit || !declare_here(name))
    {
      line(std::format("{} = {};", cpp_name(name), value.code));
      return;
    }
    // An object's handle type is long and says little; every other type is written out, so a student sees
    // it, and so a read of an object's attribute is stored as a value rather than kept as the attribute
    if (t.k == kind::object)
      line(std::format("auto {} = {};", cpp_name(name), value.code));
    else if (t.k == kind::list && value.code == "{}")
      line(std::format("{} {};", cpp_type(t, name), cpp_name(name)));
    else if (t.k == kind::list && value.code.starts_with(cpp_type(t, name) + "{"))
      line(std::format("{} {} = {};", cpp_type(t, name), cpp_name(name), value.code.substr(cpp_type(t, name).size())));
    else
      line(std::format("{} {} = {};", cpp_type(t, name), cpp_name(name), value.code));
  }

  // The variable that holds an attribute a program added to the object in `owner`, which must be a plain name
  std::string user_attribute(const json& owner, const std::string& attr, const json& s)
  {
    if (owner["_type"].string() != "Name")
      unsupported(s, std::format("adding .{} to an object that isn't in a variable", attr));
    const std::string& name = owner["id"].string();
    if (m_fn && std::ranges::find(m_fn->params, name) != m_fn->params.end())
      unsupported(s, std::format("adding .{} to an object passed into a function", attr));
    // ball.mass is ball_mass, or ball__mass if the program has a ball_mass of its own
    auto [it, added] = m_user_attributes.try_emplace({name, attr});
    if (added)
    {
      const std::string var = name + "_" + attr;
      const bool taken =
        m_names.contains(var) || std::ranges::any_of(m_user_attributes, [&](const auto& u) { return u.second == var; });
      it->second = taken ? name + "__" + attr : var;
    }
    if (is_local(name) && m_fn)
      m_fn->assigned.insert(it->second);
    if (m_shared.contains(name))
      m_shared.insert(it->second);
    return it->second;
  }

  // The top-level names a function uses, which it can reach only if they live outside vpython_program
  void collect_shared(const function_info& f)
  {
    m_shared.insert(f.globals.begin(), f.globals.end());
    walk(*f.def, [&](const json& node) {
      if (node["_type"].is_null() || node["_type"].string() != "Name")
        return;
      const std::string& name = node["id"].string();
      if (std::ranges::find(f.params, name) == f.params.end() && !f.assigned.contains(name))
        m_shared.insert(name);
    });
  }

  void declare_function(const json& def)
  {
    const json& args = def["args"];
    if (!args["vararg"].is_null() || !args["kwarg"].is_null() || !args["kwonlyargs"].items().empty() ||
        !args["posonlyargs"].items().empty())
      unsupported(def, "*args, **kwargs, keyword-only or positional-only parameters");
    if (!def["decorator_list"].items().empty())
      unsupported(def, "decorators");
    function_info f;
    f.def = &def;
    for (const auto& a : args["args"].items())
      f.params.push_back(a["arg"].string());
    // Python lines the defaults up with the last parameters
    const auto& defaults = args["defaults"].items();
    f.defaults.resize(f.params.size() - defaults.size());
    for (const auto& d : defaults)
      f.defaults.push_back(&d);
    collect_names(def["body"], f);
    m_functions.emplace(def["name"].string(), std::move(f));
  }

  // The names a function body assigns or declares global, as Python decides locals
  static void collect_names(const json& body, function_info& f)
  {
    for (const auto& s : body.items())
    {
      const std::string& t = s["_type"].string();
      if (t == "Assign")
        for (const auto& target : s["targets"].items())
          if (target["_type"].string() == "Name")
            f.assigned.insert(target["id"].string());
      if ((t == "AugAssign" || t == "For") && s["target"]["_type"].string() == "Name")
        f.assigned.insert(s["target"]["id"].string());
      if (t == "Global")
        for (const auto& n : s["names"].items())
          f.globals.insert(n.string());
      for (const char* block : {"body", "orelse"})
        if (!s[block].is_null())
          collect_names(s[block], f);
    }
  }

  // A call's arguments in parameter order. A default is computed at each call, in the program's top-level
  // scope; Python computes it once, when the def runs, which gives the same value for the constants and
  // top-level names defaults hold here.
  std::vector<expr> call_arguments(const json& e, const function_info& f)
  {
    const std::string& name = e["func"]["id"].string();
    const auto& args = e["args"].items();
    if (args.size() > f.params.size())
      throw translate_error(line_of(e), std::format("{} takes at most {} arguments", name, f.params.size()));
    std::vector<std::optional<expr>> values(f.params.size());
    for (std::size_t i = 0; i < args.size(); ++i)
      values[i] = expression(args[i]);
    for (const auto& k : e["keywords"].items())
    {
      if (k["arg"].is_null())
        unsupported(e, "**keyword arguments");
      const auto it = std::ranges::find(f.params, k["arg"].string());
      if (it == f.params.end())
        throw translate_error(line_of(e), std::format("{} has no parameter {}", name, k["arg"].string()));
      auto& given = values[static_cast<std::size_t>(it - f.params.begin())];
      if (given)
        throw translate_error(line_of(e), std::format("{} is given {} twice", name, k["arg"].string()));
      given = expression(k["value"]);
    }
    std::vector<expr> out;
    for (std::size_t i = 0; i < values.size(); ++i)
    {
      if (values[i])
        out.push_back(*values[i]);
      else if (f.defaults[i])
      {
        function_info* caller = m_fn;
        m_fn = nullptr;
        out.push_back(expression(*f.defaults[i]));
        m_fn = caller;
      }
      else
        throw translate_error(line_of(e), std::format("{} is missing its argument {}", name, f.params[i]));
    }
    return out;
  }

  expr user_call(const json& e, function_info& f)
  {
    const std::vector<expr> values = call_arguments(e, f);

    if (!f.analyzed && !f.analyzing)
    {
      f.analyzing = true;
      for (std::size_t i = 0; i < values.size(); ++i)
      {
        f.param_types.push_back(values[i].t);
        f.local_types[f.params[i]] = values[i].t;
      }
      function_info* outer = m_fn;
      m_fn = &f;
      for (const auto& stmt : (*f.def)["body"].items())
        statement(stmt);
      m_fn = outer;
      f.analyzing = false;
      f.analyzed = true;
    }
    else
      for (std::size_t i = 0; i < values.size(); ++i)
        if (!unify(f.param_types[i], values[i].t))
          unsupported(e, std::format("calling {} with arguments of different types", e["func"]["id"].string()));
    if (f.analyzing && f.returns.k == kind::unknown)
      unsupported(e, "a recursive call before the function's first return");

    std::string code;
    for (const auto& v : values)
      code += (code.empty() ? "" : ", ") + v.code;
    return {std::format("(co_await {}({}))", cpp_name(e["func"]["id"].string()), code), f.returns};
  }

  void return_statement(const json& s)
  {
    if (!m_fn)
      unsupported(s, "return outside a function");
    if (s["value"].is_null())
    {
      line("co_return;");
      return;
    }
    const expr value = expression(s["value"]);
    if (!unify(m_fn->returns, value.t))
      unsupported(s, "a function returning values of different types");
    line(std::format("co_return {};", value.code));
  }

  static std::string cpp_type(const type& t, const std::string& name)
  {
    switch (t.k)
    {
      case kind::number:
        return "double";
      case kind::boolean:
        return "bool";
      case kind::string:
        return "std::string";
      case kind::vector:
        return "vec3";
      case kind::object:
        return std::format("handle<{}_object>", t.object);
      case kind::list:
        return std::format("std::vector<{}>", cpp_type(t.element[0], name));
      default:
        throw translate_error(0, std::format("could not work out the type of {}", name));
    }
  }

  std::string signature(const std::string& name, const function_info& f) const
  {
    std::string params;
    for (std::size_t i = 0; i < f.params.size(); ++i)
    {
      // A list is passed by reference: Python functions change the caller's list, not a copy
      const char* ref = f.param_types[i].k == kind::list ? "&" : "";
      params +=
        std::format("{}{}{} {}", i ? ", " : "", cpp_type(f.param_types[i], f.params[i]), ref, cpp_name(f.params[i]));
    }
    const std::string result = f.returns.k == kind::unknown ? "void" : cpp_type(f.returns, name);
    return std::format("task<{}> {}({})", result, cpp_name(name), params);
  }

  // ---------------------------------------------------------------- expressions

  static type result_type(const type& a, const type& b)
  {
    if (a.k == kind::vector || b.k == kind::vector)
      return {kind::vector, {}};
    if (a.k == kind::number && b.k == kind::number)
      return {kind::number, {}};
    return {};
  }

  static std::string string_literal(const std::string& text)
  {
    std::string out = "\"";
    for (char c : text)
    {
      switch (c)
      {
        case '"':
          out += "\\\"";
          break;
        case '\\':
          out += "\\\\";
          break;
        case '\n':
          out += "\\n";
          break;
        case '\t':
          out += "\\t";
          break;
        default:
          out += c;
      }
    }
    return out + "\"";
  }

  expr expression(const json& e)
  {
    const std::string& t = e["_type"].string();
    if (t == "Constant")
      return constant(e);
    if (t == "Name")
      return name(e);
    if (t == "Attribute")
      return attribute_read(e);
    if (t == "BinOp")
      return binary(e);
    if (t == "UnaryOp")
      return unary(e);
    if (t == "Compare")
      return compare(e);
    if (t == "BoolOp")
      return boolean_op(e);
    if (t == "Call")
      return call(e);
    if (t == "List")
      return list_literal(e);
    if (t == "Subscript")
      return subscript(e);
    if (t == "JoinedStr")
      return formatted_string(e);
    unsupported(e, std::format("the {} expression", t));
  }

  // [a, b] is a std::vector of the elements' common type; [] is {} until something is put in it
  expr list_literal(const json& e)
  {
    type element;
    std::string code;
    for (const auto& item : e["elts"].items())
    {
      const expr v = expression(item);
      if (!unify(element, v.t))
        unsupported(e, "a list of different types");
      code += (code.empty() ? "" : ", ") + v.code;
    }
    if (code.empty())
      return {"{}", type::list_of({})};
    return {std::format("std::vector<{}>{{{}}}", cpp_type(element, "a list element"), code), type::list_of(element)};
  }

  // f"..." is std::format. A format spec carries over: Python's and std::format's agree on the usual ones,
  // such as .2f, and an integer spec (d, x, ...) formats the double as an integer. A number with no spec
  // prints as GlowScript prints it, without a trailing .0.
  expr formatted_string(const json& e)
  {
    std::string fmt;
    std::string args;
    for (const auto& part : e["values"].items())
    {
      if (part["_type"].string() == "Constant")
      {
        for (const char c : part["value"].string())
          fmt += (c == '{' || c == '}') ? std::string(2, c) : std::string(1, c);
        continue;
      }
      if (part["conversion"].num().text != "-1")
        unsupported(e, "!r, !s or !a in an f-string");
      expr v = expression(part["value"]);
      if (v.t.k != kind::number && v.t.k != kind::string && v.t.k != kind::boolean)
        unsupported(e, "formatting this kind of value in an f-string");
      std::string spec;
      if (!part["format_spec"].is_null())
        for (const auto& piece : part["format_spec"]["values"].items())
        {
          if (piece["_type"].string() != "Constant")
            unsupported(e, "a format spec worked out as the program runs");
          spec += piece["value"].string();
        }
      if (!spec.empty() && std::string_view("bcdoxX").contains(spec.back()))
        v.code = std::format("static_cast<long long>({})", v.code);
      fmt += spec.empty() ? "{}" : "{:" + spec + "}";
      args += ", " + v.code;
    }
    return {std::format("std::format({}{})", string_literal(fmt), args), {kind::string, {}}};
  }

  // a[i]; a negative literal counts from the end, as in Python
  expr subscript(const json& e)
  {
    if (const auto field = curve_point_field(e))
      return *field;
    const expr list = expression(e["value"]);
    if (list.t.k != kind::list)
      unsupported(e, "indexing something other than a list");
    const json& index = e["slice"];
    if (index["_type"].string() == "Slice")
      unsupported(e, "slices");
    const auto sign = constant_sign(index);
    std::string at;
    if (sign && *sign < 0)
      at = std::format("{}.size() - {}", list.code, index["operand"]["value"].num().text);
    else if (sign)
      at = index["value"].num().text;
    else
      at = std::format("static_cast<std::size_t>({})", expression(index).code);
    return {std::format("{}[{}]", list.code, at), list.t.element[0]};
  }

  static expr constant(const json& e)
  {
    const json& v = e["value"];
    if (v.is_null())
      unsupported(e, "None");
    if (const auto* b = std::get_if<bool>(&v.value))
      return {*b ? "true" : "false", {kind::boolean, {}}};
    if (const auto* s = std::get_if<std::string>(&v.value))
      return {string_literal(*s), {kind::string, {}}};
    // Every number is a double, as in VPython; an integer literal is written as one, and binary() makes the
    // arithmetic floating point where C++ wouldn't
    const json::number& n = v.num();
    return {n.text, {kind::number, {}}, n.text.starts_with('-') ? p_unary : p_atom, n.is_integer};
  }

  expr name(const json& e)
  {
    const std::string& id = e["id"].string();
    if (id == "pi")
      return {"std::numbers::pi", {kind::number, {}}};
    const type& t = slot(id);
    if (t.k == kind::unknown)
      throw translate_error(line_of(e), std::format("{} is used before it is assigned", id));
    return {cpp_name(id), t};
  }

  expr attribute_read(const json& e)
  {
    const json& base = e["value"];
    const std::string& attr = e["attr"].string();

    if (base["_type"].string() == "Name" && base["id"].string() == "color")
      return {std::format("colors::{}", attr), {kind::vector, {}}};
    if (base["_type"].string() == "Name" && base["id"].string() == "textures")
      return {std::format("textures::{}", attr), {kind::string, {}}};

    const expr owner = expression(base);
    if (owner.t.k == kind::object)
    {
      const auto k = object_attribute(attr);
      if (!k)
      {
        const std::string var = user_attribute(base, attr, e);
        const type& t = slot(var);
        if (t.k == kind::unknown)
          throw translate_error(line_of(e), std::format("{}.{} is used before it is assigned", owner.code, attr));
        return {cpp_name(var), t};
      }
      return {std::format("{}.{}", paren(owner, p_atom), attr), {*k, {}}};
    }
    if (owner.t.k == kind::vector)
    {
      if (attr == "x" || attr == "y" || attr == "z")
        return {std::format("{}.{}()", paren(owner, p_atom), attr), {kind::number, {}}};
      if (attr == "mag")
        return {std::format("mag({})", owner.code), {kind::number, {}}};
      if (attr == "mag2")
        return {std::format("mag2({})", owner.code), {kind::number, {}}};
      if (attr == "hat")
        return {std::format("hat({})", owner.code), {kind::vector, {}}};
    }
    unsupported(e, std::format("reading .{} here", attr));
  }

  expr binary(const json& e)
  {
    const std::string& op = e["op"]["_type"].string();
    const expr l = expression(e["left"]);
    const expr r = expression(e["right"]);
    const type t = result_type(l.t, r.t);
    if (op == "Pow")
      return {std::format("std::pow({}, {})", l.code, r.code), {kind::number, {}}};
    if (op == "FloorDiv")
      return {
        std::format("std::floor({} / {})", paren({as_double(l), {}, l.prec}, p_multiply), paren(r, p_multiply + 1)),
        {kind::number, {}}};
    if (op == "Mod")
      return {std::format("std::fmod({}, {})", l.code, r.code), {kind::number, {}}};
    static const std::map<std::string_view, std::string_view> ops{
      {"Add", "+"}, {"Sub", "-"}, {"Mult", "*"}, {"Div", "/"}};
    const auto it = ops.find(op);
    if (it == ops.end())
      unsupported(e, std::format("the operator {}", op));
    const int prec = op == "Add" || op == "Sub" ? p_add : p_multiply;
    std::string left = paren(l, prec);
    std::string right = paren(r, prec + 1); // a - (b - c) keeps its parentheses, as does a * (b * c)
    if (op == "Div" && l.integer && r.integer)
      left = paren({as_double(l), {}, l.prec}, prec); // Python's 1/2 is 0.5
    if (l.t.k == kind::vector && r.t.k == kind::number)
      right = paren({as_double(r), {}, r.prec}, prec + 1);
    if (r.t.k == kind::vector && l.t.k == kind::number)
      left = paren({as_double(l), {}, l.prec}, prec);
    return {std::format("{} {} {}", left, it->second, right), t, prec, l.integer && r.integer && op != "Div"};
  }

  expr unary(const json& e)
  {
    const std::string& op = e["op"]["_type"].string();
    const expr v = expression(e["operand"]);
    if (op == "USub")
      return {"-" + paren(v, p_unary + 1), v.t, p_unary, v.integer}; // p_unary + 1: - -x, not --x
    if (op == "UAdd")
      return v;
    if (op == "Not")
      return {"!" + paren(v, p_unary + 1), {kind::boolean, {}}, p_unary};
    unsupported(e, std::format("the operator {}", op));
  }

  // a < b < c is a < b && b < c, as in Python
  expr compare(const json& e)
  {
    static const std::map<std::string_view, std::string_view> ops{{"Lt", "<"},   {"LtE", "<="}, {"Gt", ">"},
                                                                  {"GtE", ">="}, {"Eq", "=="},  {"NotEq", "!="}};
    std::string left = paren(expression(e["left"]), p_compare + 1);
    std::vector<std::string> parts;
    const auto& operators = e["ops"].items();
    const auto& comparators = e["comparators"].items();
    for (std::size_t i = 0; i < operators.size(); ++i)
    {
      const auto it = ops.find(operators[i]["_type"].string());
      if (it == ops.end())
        unsupported(e, std::format("the comparison {}", operators[i]["_type"].string()));
      const std::string right = paren(expression(comparators[i]), p_compare + 1);
      parts.push_back(std::format("{} {} {}", left, it->second, right));
      left = right;
    }
    std::string code = parts[0];
    for (std::size_t i = 1; i < parts.size(); ++i)
      code += " && " + parts[i];
    return {code, {kind::boolean, {}}, parts.size() > 1 ? p_and : p_compare};
  }

  expr boolean_op(const json& e)
  {
    const bool conjunction = e["op"]["_type"].string() == "And";
    std::string code;
    for (const auto& v : e["values"].items()) // an && inside || is parenthesised, as compilers ask
      code += (code.empty() ? "" : conjunction ? " && " : " || ") + paren(expression(v), p_and + 1);
    return {code, {kind::boolean, {}}, conjunction ? p_and : p_or};
  }

  expr call(const json& e)
  {
    const json& func = e["func"];
    if (func["_type"].string() == "Attribute")
    {
      const json& base = func["value"];
      if (base["_type"].string() == "Name" && base["id"].string() == "color")
        return {std::format("colors::{}({})", func["attr"].string(), arguments(e)), {kind::vector, {}}};
      if (func["attr"].string() == "append" && expression(base).t.k == kind::list)
        return append(e);
      if (func["attr"].string() == "rotate")
        return rotate_call(e, &base);
      if (func["attr"].string() == "random" && base["_type"].string() == "Name" &&
          (base["id"].string() == "vec" || base["id"].string() == "vector") && e["args"].items().empty())
        return {"random_vec()", {kind::vector, {}}};
      if (base["_type"].string() == "Name" && base["id"].string() == "scene" &&
          (func["attr"].string() == "append_to_title" || func["attr"].string() == "append_to_caption"))
        return append_text(e);
      static constexpr std::array curve_methods{"append", "modify", "clear"};
      if (std::ranges::find(curve_methods, func["attr"].string()) != curve_methods.end() && is_curve(base))
        return curve_method(e);
      unsupported(e, std::format("calling .{}()", func["attr"].string()));
    }
    if (func["_type"].string() != "Name")
      unsupported(e, "this kind of call");
    const std::string& f = func["id"].string();

    if (m_functions.contains(f))
      return user_call(e, m_functions.at(f));
    if (f == "vector" || f == "vec")
      return {std::format("vec3{{{}}}", arguments(e)), {kind::vector, {}}};
    if (f == "rate" || f == "sleep")
      return {std::format("{}({})", f, arguments(e)), {}};
    if (f == "rotate")
      return rotate_call(e, nullptr);
    if (f == "random" && e["args"].items().empty())
      return {"random()", {kind::number, {}}};
    if (f == "len")
    {
      if (e["args"].items().size() != 1 || expression(e["args"].items()[0]).t.k != kind::list)
        unsupported(e, "len() of something other than a list");
      return {std::format("static_cast<double>({}.size())", arguments(e)), {kind::number, {}}};
    }
    if (is_object_factory(f))
      return {std::format("{}({})", vcpp_factory(f), keyword_arguments(e)),
              {kind::object, std::string(vcpp_factory(f))}};
    static const std::map<std::string_view, std::pair<std::string_view, kind>> functions{
      {"mag", {"mag", kind::number}},          {"mag2", {"mag2", kind::number}},
      {"norm", {"hat", kind::vector}},         {"hat", {"hat", kind::vector}},
      {"cross", {"cross", kind::vector}},      {"dot", {"dot", kind::number}},
      {"sqrt", {"std::sqrt", kind::number}},   {"sin", {"std::sin", kind::number}},
      {"cos", {"std::cos", kind::number}},     {"tan", {"std::tan", kind::number}},
      {"atan2", {"std::atan2", kind::number}}, {"exp", {"std::exp", kind::number}},
      {"log", {"std::log", kind::number}},     {"abs", {"std::abs", kind::number}}};
    if (const auto it = functions.find(f); it != functions.end())
      return {std::format("{}({})", it->second.first, arguments(e)), {it->second.second, {}}};
    unsupported(e, std::format("calling {}()", f));
  }

  // list.append(x); the list's element type is learned here when it was made empty
  expr append(const json& e)
  {
    const json& base = e["func"]["value"];
    const auto& args = e["args"].items();
    if (args.size() != 1 || !e["keywords"].items().empty())
      unsupported(e, "append() with other than one argument");
    const expr value = expression(args[0]);
    type* list = variable_type(base);
    if (!list)
      unsupported(e, "appending to a list that isn't in a variable");
    if (!unify(list->element[0], value.t))
      unsupported(e, "a list of different types");
    return {std::format("{}.push_back({})", expression(base).code, value.code), {}};
  }

  bool is_curve(const json& e)
  {
    const expr owner = expression(e);
    return owner.t.k == kind::object && owner.t.object == "curve";
  }

  // A point's index as curve::point and modify take it
  std::string point_index(const json& e)
  {
    const expr n = expression(e);
    return n.integer ? n.code : std::format("static_cast<std::ptrdiff_t>({})", n.code);
  }

  // GlowScript's curve methods: c.append(v), c.append([v, ...]), c.append(pos=v, color=c, radius=r),
  // c.modify(n, v) or c.modify(n, color=c, ...), c.clear()
  expr curve_method(const json& e)
  {
    const std::string& method = e["func"]["attr"].string();
    const std::string owner = expression(e["func"]["value"]).code;
    const auto& args = e["args"].items();
    const auto keywords = [&](std::string code) {
      for (const auto& k : e["keywords"].items())
      {
        if (k["arg"].is_null())
          unsupported(e, "**keyword arguments");
        const std::string& name = k["arg"].string();
        if (name != "pos" && name != "color" && name != "radius")
          unsupported(e, std::format("a curve point's {}", name));
        code += std::format("{}{} = {}", code.empty() ? "" : ", ", name, expression(k["value"]).code);
      }
      return code;
    };
    if (method == "append")
    {
      if (args.size() + e["keywords"].items().size() == 0 || (!args.empty() && !e["keywords"].items().empty()))
        unsupported(e, "this form of curve append()");
      if (args.size() > 1)
        unsupported(e, "curve append() of several points; pass a list");
      if (args.empty())
        return {std::format("{}.append({})", owner, keywords("")), {}};
      const expr point = expression(args[0]);
      if (point.t.k == kind::list && point.t.element[0].k != kind::vector)
        unsupported(e, "appending curve points as dictionaries");
      if (point.t.k != kind::vector && point.t.k != kind::list)
        unsupported(e, "appending this to a curve");
      return {std::format("{}.append({})", owner, point.code), {}};
    }
    if (method == "modify")
    {
      if (args.empty() || args.size() > 2 || (args.size() == 2 && !e["keywords"].items().empty()))
        unsupported(e, "this form of curve modify()");
      const std::string n = point_index(args[0]);
      if (args.size() == 2)
        return {std::format("{}.modify({}, {})", owner, n, expression(args[1]).code), {}};
      return {std::format("{}.modify({})", owner, keywords(n)), {}};
    }
    if (method == "clear" && args.empty() && e["keywords"].items().empty())
      return {std::format("{}.clear()", owner), {}};
    unsupported(e, std::format("calling .{}() on a curve", method));
  }

  // c.point(n)['pos'] (or 'color', 'radius'): GlowScript's point() returns a dictionary, vcpp's a curve_point
  std::optional<expr> curve_point_field(const json& e)
  {
    const json& call = e["value"];
    const json& key = e["slice"];
    if (call["_type"].string() != "Call" || call["func"]["_type"].string() != "Attribute" ||
        call["func"]["attr"].string() != "point" || !is_curve(call["func"]["value"]))
      return std::nullopt;
    const auto& args = call["args"].items();
    if (args.size() != 1 || !call["keywords"].items().empty())
      unsupported(e, "this form of curve point()");
    const auto* field = key["_type"].string() == "Constant" ? std::get_if<std::string>(&key["value"].value) : nullptr;
    static const std::map<std::string_view, kind> fields{
      {"pos", kind::vector}, {"color", kind::vector}, {"radius", kind::number}};
    if (!field || !fields.contains(*field))
      unsupported(e, "this field of a curve point");
    return expr{std::format("{}.point({}).{}", expression(call["func"]["value"]).code, point_index(args[0]), *field),
                {fields.at(*field), {}}};
  }

  // obj.rotate(angle, axis, origin) turns an object; v.rotate(angle, axis) and rotate(v, angle, axis) turn a
  // vector. Each argument may be given by position or by name, as in GlowScript.
  expr rotate_call(const json& e, const json* owner_node)
  {
    std::vector<const json*> given;
    const json* owner = owner_node;
    for (const auto& a : e["args"].items())
      if (!owner)
        owner = &a; // rotate(v, ...)
      else
        given.push_back(&a);
    const std::array<std::string_view, 3> names{"angle", "axis", "origin"};
    given.resize(3, nullptr);
    for (const auto& k : e["keywords"].items())
    {
      const auto it = std::ranges::find(names, k["arg"].is_null() ? "" : k["arg"].string());
      if (it == names.end())
        unsupported(e, "this argument to rotate()");
      given[static_cast<std::size_t>(it - names.begin())] = &k["value"];
    }
    if (!owner || !given[0])
      unsupported(e, "rotate() without an angle");
    const expr target = expression(*owner);
    std::vector<std::string> args{expression(*given[0]).code};
    for (std::size_t i = 1; i < 3; ++i)
      args.push_back(given[i] ? expression(*given[i]).code : "{}");
    while (args.back() == "{}")
      args.pop_back();
    std::string list;
    for (const auto& a : args)
      list += (list.empty() ? "" : ", ") + a;
    if (target.t.k == kind::object)
      return {std::format("{}.rotate({})", target.code, list), {}};
    if (target.t.k == kind::vector)
    {
      if (given[2])
        unsupported(e, "rotating a vector about an origin");
      return {std::format("rotate({}, {})", target.code, list), {kind::vector, {}}};
    }
    unsupported(e, "rotating this kind of value");
  }

  // scene.append_to_title(a, b, ...) adds the arguments' text, separated by spaces, as GlowScript does
  expr append_text(const json& e)
  {
    if (!e["keywords"].items().empty())
      unsupported(e, "keyword arguments here");
    const auto& args = e["args"].items();
    std::string text;
    if (args.size() == 1 && expression(args[0]).t.k == kind::string)
      text = expression(args[0]).code;
    else
    {
      std::string fmt;
      std::string values;
      for (const auto& a : args)
      {
        fmt += fmt.empty() ? "{}" : " {}";
        values += ", " + expression(a).code;
      }
      text = std::format("std::format(\"{}\"{})", fmt, values);
    }
    return {std::format("scene.{}({})", e["func"]["attr"].string(), text), {}};
  }

  // The recorded type of a variable, or of an attribute a program added to an object; null for anything else
  type* variable_type(const json& e)
  {
    const std::string& t = e["_type"].string();
    if (t == "Name")
      return &slot(e["id"].string());
    if (t == "Attribute" && expression(e["value"]).t.k == kind::object && !object_attribute(e["attr"].string()))
      return &slot(user_attribute(e["value"], e["attr"].string(), e));
    return nullptr;
  }

  std::string arguments(const json& e)
  {
    if (!e["keywords"].items().empty())
      unsupported(e, "keyword arguments here");
    std::string code;
    for (const auto& a : e["args"].items())
      code += (code.empty() ? "" : ", ") + expression(a).code;
    return code;
  }

  // VPython objects are built from keyword arguments, which map to vcpp's named parameters
  std::string keyword_arguments(const json& e)
  {
    if (!e["args"].items().empty())
      unsupported(e, "positional arguments to an object");
    std::string code;
    for (const auto& k : e["keywords"].items())
    {
      if (k["arg"].is_null())
        unsupported(e, "**keyword arguments");
      const std::string& name = k["arg"].string();
      code += std::format("{}{} = {}", code.empty() ? "" : ", ", name, expression(k["value"]).code);
    }
    return code;
  }
};

} // namespace vpy2cpp
