/*
 *  vpy2cpp:emit - Writes a VPython program, given as vpy_ast.py's JSON, as vcpp C++
 *
 *  The output is one coroutine, vpython_program(), for vcpp's run_program(). Each VPython statement is
 *  translated where vcpp has an equivalent; anything else stops translation with the line it is on.
 */

module;

import std;

export module vpy2cpp:emit;

import :json;

export namespace vpy2cpp
{

struct translate_error : std::runtime_error
{
  int line;
  translate_error(int l, const std::string& what) : std::runtime_error(what), line(l) {}
};

class emitter
{
public:
  std::string program(const json& module)
  {
    m_out.clear();
    m_depth = 1;
    for (const auto& stmt : module["body"].items())
      statement(stmt);
    return "// Generated by vpy2cpp from a VPython program.\n\nimport std;\nimport vcpp;\nimport lam.linearalgebra;\n\n"
           "using namespace vcpp;\n\ntask<void> vpython_program()\n{\n" +
           m_out + "}\n";
  }

private:
  enum class kind
  {
    unknown,
    number,
    boolean,
    string,
    vector,
    object
  };

  struct type
  {
    kind k = kind::unknown;
    std::string object; // the vcpp factory for an object: "box", "sphere", ...
  };

  struct expr
  {
    std::string code;
    type t;
  };

  // How a VPython object attribute is read and written in vcpp
  struct attribute
  {
    std::string_view member; // read as handle->member
    std::string_view setter; // written with handle.setter(value); empty: write the member
    kind k;
  };

  std::string m_out;
  int m_depth = 1;
  std::map<std::string, type> m_vars;             // VPython name -> type
  std::map<std::string, std::string> m_user_attr; // "ball.mass" -> C++ variable

  // ---------------------------------------------------------------- names

  static bool is_object_factory(std::string_view name)
  {
    static constexpr std::array names{"box",   "sphere", "cylinder", "cone",   "pyramid", "ellipsoid", "ring",
                                      "helix", "arrow",  "curve",    "points", "label",   "text",      "extrusion"};
    return std::ranges::find(names, name) != names.end();
  }

  static std::string_view vcpp_factory(std::string_view name) { return name == "text" ? "text3d" : name; }

  // Names a program variable can't keep: vcpp's named-parameter symbols and functions, and C++ keywords
  static bool reserved(std::string_view name)
  {
    static const std::set<std::string_view> names{
      // vcpp named parameters (vcpp-props.cppm)
      "acceleration", "align", "ambient", "axis", "background", "billboard", "border", "box", "caption", "ccw",
      "center", "charge", "closed", "coils", "color", "delta", "depth", "dot_color", "dot_radius", "dt", "emissive",
      "fast", "font", "foreground", "forward", "fov", "graph_ref", "group", "headlength", "headwidth", "height",
      "interval", "label", "legend", "length", "lights", "line", "make_trail", "marker_radius", "markers", "mass",
      "momentum", "normal", "opacity", "path", "points", "pos", "radius", "range", "retain", "round", "scale_end",
      "shaftwidth", "shape", "shininess", "show_dot", "show_end_face", "show_start_face", "size", "target_canvas",
      "texpos", "text", "texture", "thickness", "title", "trail_color", "trail_radius", "twist", "up", "v0", "v1", "v2",
      "v3", "velocity", "visible", "width", "xmax", "xmin", "xoffset", "xtitle", "ymax", "ymin", "yoffset", "ytitle",
      // vcpp functions and objects the generated code uses
      "scene", "rate", "sleep", "vec3", "vec2", "colors", "mag", "hat", "norm", "cross", "dot", "task",
      // C++ keywords that are valid Python names
      "auto", "bool", "break", "case", "catch", "char", "class", "const", "default", "delete", "do", "double", "enum",
      "explicit", "extern", "float", "friend", "goto", "inline", "int", "long", "mutable", "namespace", "new",
      "operator", "private", "protected", "public", "register", "short", "signed", "sizeof", "static", "struct",
      "switch", "template", "this", "throw", "typedef", "typename", "union", "unsigned", "using", "virtual", "void",
      "volatile"};
    return names.contains(name) || is_object_factory(name);
  }

  static std::string cpp_name(const std::string& name) { return reserved(name) ? name + "_" : name; }

  // ---------------------------------------------------------------- helpers

  static int line_of(const json& node)
  {
    const json& l = node["lineno"];
    return l.is_null() ? 0 : std::stoi(l.num().text);
  }

  [[noreturn]] static void unsupported(const json& node, std::string_view what)
  { throw translate_error(line_of(node), std::format("not supported yet: {}", what)); }

  void line(const std::string& text)
  {
    m_out.append(static_cast<std::size_t>(m_depth) * 2, ' ');
    m_out += text;
    m_out += '\n';
  }

  static std::optional<attribute> object_attribute(std::string_view name)
  {
    static const std::map<std::string_view, attribute> attrs{
      {"pos", {"m_pos", "set_pos", kind::vector}},
      {"axis", {"m_axis", "set_axis", kind::vector}},
      {"up", {"m_up", "set_up", kind::vector}},
      {"size", {"", "set_size", kind::vector}},
      {"length", {"m_length", "set_length", kind::number}},
      {"height", {"m_height", "", kind::number}},
      {"width", {"m_width", "", kind::number}},
      {"radius", {"m_radius", "", kind::number}},
      {"thickness", {"m_thickness", "", kind::number}},
      {"color", {"m_color", "", kind::vector}},
      {"trail_color", {"m_trail_color", "", kind::vector}},
      {"opacity", {"m_opacity", "", kind::number}},
      {"shininess", {"m_shininess", "", kind::number}},
      {"visible", {"m_visible", "", kind::boolean}},
      {"make_trail", {"m_make_trail", "", kind::boolean}},
      {"emissive", {"m_emissive", "", kind::boolean}},
      {"retain", {"m_retain", "", kind::number}},
      {"interval", {"m_interval", "", kind::number}},
    };
    const auto it = attrs.find(name);
    return it == attrs.end() ? std::nullopt : std::optional{it->second};
  }

  // ---------------------------------------------------------------- statements

  void statement(const json& s)
  {
    const std::string& t = s["_type"].string();
    if (t == "Expr")
      expression_statement(s);
    else if (t == "Assign")
      assign(s);
    else if (t == "AugAssign")
      aug_assign(s);
    else if (t == "While")
      while_loop(s);
    else if (t == "If")
      if_chain(s);
    else if (t == "Pass")
      line(";");
    else if (t == "Break")
      line("break;");
    else if (t == "Continue")
      line("continue;");
    else
      unsupported(s, std::format("the {} statement", t));
  }

  void block(const json& body)
  {
    ++m_depth;
    for (const auto& stmt : body.items())
      statement(stmt);
    --m_depth;
  }

  void expression_statement(const json& s)
  {
    const json& value = s["value"];
    const std::string& t = value["_type"].string();
    if (t == "Constant" && std::holds_alternative<std::string>(value["value"].value))
      return; // a docstring
    if (t == "Call" && value["func"]["_type"].string() == "Name")
    {
      const std::string& f = value["func"]["id"].string();
      if (f == "rate" || f == "sleep")
      {
        line(std::format("co_await {};", call(value).code));
        return;
      }
      if (is_object_factory(f))
      {
        line(std::format("scene.add({});", call(value).code));
        return;
      }
    }
    line(expression(value).code + ";");
  }

  void assign(const json& s)
  {
    const auto& targets = s["targets"].items();
    if (targets.size() != 1)
      unsupported(s, "assigning to several targets at once");
    assign_to(targets[0], s["value"], s);
  }

  void assign_to(const json& target, const json& value_node, const json& s)
  {
    const std::string& t = target["_type"].string();
    if (t == "Name")
    {
      const std::string& name = target["id"].string();
      expr value = expression(value_node);
      if (value.t.k == kind::object)
        value.code = std::format("scene.add({})", value.code);
      if (m_vars.contains(name))
        line(std::format("{} = {};", cpp_name(name), value.code));
      else
      {
        line(std::format("auto {} = {};", cpp_name(name), value.code));
        m_vars[name] = value.t;
      }
      return;
    }
    if (t == "Attribute")
    {
      assign_attribute(target, expression(value_node), s);
      return;
    }
    unsupported(s, std::format("assigning to a {}", t));
  }

  void assign_attribute(const json& target, const expr& value, const json& s)
  {
    const json& base = target["value"];
    const std::string& attr = target["attr"].string();

    if (base["_type"].string() == "Name" && base["id"].string() == "scene")
    {
      static const std::map<std::string_view, std::string_view> scene_attrs{
        {"caption", "m_caption"}, {"title", "m_title"}, {"background", "m_background"}, {"autoscale", "m_autoscale"}};
      const auto it = scene_attrs.find(attr);
      if (it == scene_attrs.end())
        unsupported(s, std::format("setting scene.{}", attr));
      line(std::format("scene.{} = {};", it->second, value.code));
      return;
    }

    const expr owner = expression(base);
    if (owner.t.k == kind::object)
    {
      if (const auto a = object_attribute(attr))
      {
        if (!a->setter.empty())
          line(std::format("{}.{}({});", owner.code, a->setter, value.code));
        else
          line(std::format("{}->{} = {};", owner.code, a->member, value.code));
        return;
      }
      // VPython objects take new attributes; each becomes a variable of its own
      const std::string key = owner.code + "." + attr;
      if (const auto it = m_user_attr.find(key); it != m_user_attr.end())
        line(std::format("{} = {};", it->second, value.code));
      else
      {
        const std::string var = owner.code + "__" + attr;
        line(std::format("auto {} = {};", var, value.code));
        m_user_attr[key] = var;
        m_vars[key] = value.t;
      }
      return;
    }
    if (owner.t.k == kind::vector && (attr == "x" || attr == "y" || attr == "z"))
    {
      line(std::format("{}.{}() = {};", owner.code, attr, value.code));
      return;
    }
    unsupported(s, std::format("setting .{} here", attr));
  }

  void aug_assign(const json& s)
  {
    static const std::map<std::string_view, std::string_view> ops{
      {"Add", "+"}, {"Sub", "-"}, {"Mult", "*"}, {"Div", "/"}};
    const auto it = ops.find(s["op"]["_type"].string());
    if (it == ops.end())
      unsupported(s, std::format("the augmented operator {}", s["op"]["_type"].string()));
    // target op= value is target = target op value, which also routes attributes through their setters
    const expr current = expression(s["target"]);
    const expr value = expression(s["value"]);
    expr sum{std::format("{} {} ({})", current.code, it->second, value.code), result_type(current.t, value.t)};
    assign_computed(s["target"], sum, s);
  }

  void assign_computed(const json& target, const expr& value, const json& s)
  {
    const std::string& t = target["_type"].string();
    if (t == "Name")
    {
      const std::string& name = target["id"].string();
      if (!m_vars.contains(name))
        throw translate_error(line_of(s), std::format("{} is used before it is assigned", name));
      line(std::format("{} = {};", cpp_name(name), value.code));
    }
    else if (t == "Attribute")
      assign_attribute(target, value, s);
    else
      unsupported(s, std::format("updating a {}", t));
  }

  void while_loop(const json& s)
  {
    if (!s["orelse"].items().empty())
      unsupported(s, "while ... else");
    line(std::format("while ({})", condition(s["test"])));
    line("{");
    block(s["body"]);
    line("}");
  }

  void if_chain(const json& s, std::string_view prefix = "")
  {
    line(std::format("{}if ({})", prefix, condition(s["test"])));
    line("{");
    block(s["body"]);
    line("}");
    const auto& orelse = s["orelse"].items();
    if (orelse.empty())
      return;
    if (orelse.size() == 1 && orelse[0]["_type"].string() == "If")
    {
      if_chain(orelse[0], "else "); // elif
      return;
    }
    line("else");
    line("{");
    block(s["orelse"]);
    line("}");
  }

  std::string condition(const json& test)
  {
    const expr e = expression(test);
    return e.code;
  }

  // ---------------------------------------------------------------- expressions

  static type result_type(const type& a, const type& b)
  {
    if (a.k == kind::vector || b.k == kind::vector)
      return {kind::vector, {}};
    if (a.k == kind::number && b.k == kind::number)
      return {kind::number, {}};
    return {};
  }

  // Python's int and float literals both become doubles: VPython arithmetic is floating point, and
  // `1/2` must stay 0.5
  static std::string double_literal(const json::number& n) { return n.is_integer ? n.text + ".0" : n.text; }

  static std::string string_literal(const std::string& text)
  {
    std::string out = "\"";
    for (char c : text)
    {
      switch (c)
      {
        case '"':
          out += "\\\"";
          break;
        case '\\':
          out += "\\\\";
          break;
        case '\n':
          out += "\\n";
          break;
        case '\t':
          out += "\\t";
          break;
        default:
          out += c;
      }
    }
    return out + "\"";
  }

  expr expression(const json& e)
  {
    const std::string& t = e["_type"].string();
    if (t == "Constant")
      return constant(e);
    if (t == "Name")
      return name(e);
    if (t == "Attribute")
      return attribute_read(e);
    if (t == "BinOp")
      return binary(e);
    if (t == "UnaryOp")
      return unary(e);
    if (t == "Compare")
      return compare(e);
    if (t == "BoolOp")
      return boolean_op(e);
    if (t == "Call")
      return call(e);
    unsupported(e, std::format("the {} expression", t));
  }

  static expr constant(const json& e)
  {
    const json& v = e["value"];
    if (v.is_null())
      unsupported(e, "None");
    if (const auto* b = std::get_if<bool>(&v.value))
      return {*b ? "true" : "false", {kind::boolean, {}}};
    if (const auto* s = std::get_if<std::string>(&v.value))
      return {string_literal(*s), {kind::string, {}}};
    return {double_literal(v.num()), {kind::number, {}}};
  }

  expr name(const json& e) const
  {
    const std::string& id = e["id"].string();
    if (id == "pi")
      return {"std::numbers::pi", {kind::number, {}}};
    const auto it = m_vars.find(id);
    if (it == m_vars.end())
      throw translate_error(line_of(e), std::format("{} is used before it is assigned", id));
    return {cpp_name(id), it->second};
  }

  expr attribute_read(const json& e)
  {
    const json& base = e["value"];
    const std::string& attr = e["attr"].string();

    if (base["_type"].string() == "Name" && base["id"].string() == "color")
      return {std::format("colors::{}", attr), {kind::vector, {}}};

    const expr owner = expression(base);
    if (owner.t.k == kind::object)
    {
      if (const auto it = m_user_attr.find(owner.code + "." + attr); it != m_user_attr.end())
        return {it->second, m_vars.at(owner.code + "." + attr)};
      const auto a = object_attribute(attr);
      if (!a || a->member.empty())
        unsupported(e, std::format("reading .{} of a {}", attr, owner.t.object));
      return {std::format("{}->{}", owner.code, a->member), {a->k, {}}};
    }
    if (owner.t.k == kind::vector)
    {
      if (attr == "x" || attr == "y" || attr == "z")
        return {std::format("{}.{}()", owner.code, attr), {kind::number, {}}};
      if (attr == "mag")
        return {std::format("mag({})", owner.code), {kind::number, {}}};
      if (attr == "mag2")
        return {std::format("mag2({})", owner.code), {kind::number, {}}};
      if (attr == "hat")
        return {std::format("hat({})", owner.code), {kind::vector, {}}};
    }
    unsupported(e, std::format("reading .{} here", attr));
  }

  expr binary(const json& e)
  {
    const std::string& op = e["op"]["_type"].string();
    const expr l = expression(e["left"]);
    const expr r = expression(e["right"]);
    const type t = result_type(l.t, r.t);
    if (op == "Pow")
      return {std::format("std::pow({}, {})", l.code, r.code), {kind::number, {}}};
    if (op == "FloorDiv")
      return {std::format("std::floor({} / {})", l.code, r.code), {kind::number, {}}};
    if (op == "Mod")
      return {std::format("std::fmod({}, {})", l.code, r.code), {kind::number, {}}};
    static const std::map<std::string_view, std::string_view> ops{
      {"Add", "+"}, {"Sub", "-"}, {"Mult", "*"}, {"Div", "/"}};
    const auto it = ops.find(op);
    if (it == ops.end())
      unsupported(e, std::format("the operator {}", op));
    return {std::format("({} {} {})", l.code, it->second, r.code), t};
  }

  expr unary(const json& e)
  {
    const std::string& op = e["op"]["_type"].string();
    const expr v = expression(e["operand"]);
    if (op == "USub")
      return {std::format("-{}", v.code), v.t};
    if (op == "UAdd")
      return v;
    if (op == "Not")
      return {std::format("!({})", v.code), {kind::boolean, {}}};
    unsupported(e, std::format("the operator {}", op));
  }

  // a < b < c is a < b && b < c, as in Python
  expr compare(const json& e)
  {
    static const std::map<std::string_view, std::string_view> ops{{"Lt", "<"},   {"LtE", "<="}, {"Gt", ">"},
                                                                  {"GtE", ">="}, {"Eq", "=="},  {"NotEq", "!="}};
    std::string left = expression(e["left"]).code;
    std::vector<std::string> parts;
    const auto& operators = e["ops"].items();
    const auto& comparators = e["comparators"].items();
    for (std::size_t i = 0; i < operators.size(); ++i)
    {
      const auto it = ops.find(operators[i]["_type"].string());
      if (it == ops.end())
        unsupported(e, std::format("the comparison {}", operators[i]["_type"].string()));
      const std::string right = expression(comparators[i]).code;
      parts.push_back(std::format("{} {} {}", left, it->second, right));
      left = right;
    }
    std::string code = parts[0];
    for (std::size_t i = 1; i < parts.size(); ++i)
      code += " && " + parts[i];
    return {parts.size() > 1 ? "(" + code + ")" : code, {kind::boolean, {}}};
  }

  expr boolean_op(const json& e)
  {
    const std::string_view op = e["op"]["_type"].string() == "And" ? " && " : " || ";
    std::string code;
    for (const auto& v : e["values"].items())
      code += (code.empty() ? "" : std::string(op)) + expression(v).code;
    return {"(" + code + ")", {kind::boolean, {}}};
  }

  expr call(const json& e)
  {
    const json& func = e["func"];
    if (func["_type"].string() == "Attribute")
    {
      const json& base = func["value"];
      if (base["_type"].string() == "Name" && base["id"].string() == "color")
        return {std::format("colors::{}({})", func["attr"].string(), arguments(e)), {kind::vector, {}}};
      unsupported(e, std::format("calling .{}()", func["attr"].string()));
    }
    if (func["_type"].string() != "Name")
      unsupported(e, "this kind of call");
    const std::string& f = func["id"].string();

    if (f == "vector" || f == "vec")
      return {std::format("vec3{{{}}}", arguments(e)), {kind::vector, {}}};
    if (f == "rate" || f == "sleep")
      return {std::format("{}({})", f, arguments(e)), {}};
    if (is_object_factory(f))
      return {std::format("{}({})", vcpp_factory(f), keyword_arguments(e)),
              {kind::object, std::string(vcpp_factory(f))}};
    static const std::map<std::string_view, std::pair<std::string_view, kind>> functions{
      {"mag", {"mag", kind::number}},          {"mag2", {"mag2", kind::number}},
      {"norm", {"hat", kind::vector}},         {"hat", {"hat", kind::vector}},
      {"cross", {"cross", kind::vector}},      {"dot", {"dot", kind::number}},
      {"sqrt", {"std::sqrt", kind::number}},   {"sin", {"std::sin", kind::number}},
      {"cos", {"std::cos", kind::number}},     {"tan", {"std::tan", kind::number}},
      {"atan2", {"std::atan2", kind::number}}, {"exp", {"std::exp", kind::number}},
      {"log", {"std::log", kind::number}},     {"abs", {"std::abs", kind::number}}};
    if (const auto it = functions.find(f); it != functions.end())
      return {std::format("{}({})", it->second.first, arguments(e)), {it->second.second, {}}};
    unsupported(e, std::format("calling {}()", f));
  }

  std::string arguments(const json& e)
  {
    if (!e["keywords"].items().empty())
      unsupported(e, "keyword arguments here");
    std::string code;
    for (const auto& a : e["args"].items())
      code += (code.empty() ? "" : ", ") + expression(a).code;
    return code;
  }

  // VPython objects are built from keyword arguments, which map to vcpp's named parameters
  std::string keyword_arguments(const json& e)
  {
    if (!e["args"].items().empty())
      unsupported(e, "positional arguments to an object");
    static const std::set<std::string_view> integer_params{"retain", "interval", "coils"};
    std::string code;
    for (const auto& k : e["keywords"].items())
    {
      if (k["arg"].is_null())
        unsupported(e, "**keyword arguments");
      const std::string& name = k["arg"].string();
      std::string value = expression(k["value"]).code;
      const json& v = k["value"];
      if (integer_params.contains(name) && v["_type"].string() == "Constant")
        value = v["value"].num().text; // these parameters are ints in vcpp
      code += std::format("{}{} = {}", code.empty() ? "" : ", ", name, value);
    }
    return code;
  }
};

} // namespace vpy2cpp
